### ISSUE TITLE
pip3 install doesn't work

### ISSUE THREAD

**Issue by ronenmagid** [zerobounce/zerobounce-python-api#5]
```
Collecting zerobounce
  Downloading https://files.pythonhosted.org/packages/f6/45/c064368502a3bc44043584494624f9e8cce0c48039cb594d95a30ba5ba1b/zerobounce-0.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3k/9y9v3h2j32xb1f804pwqfb780000gn/T/pip-install-h_c38kh2/zerobounce/setup.py", line 5, in <module>
        import pypandoc
    ModuleNotFoundError: No module named 'pypandoc'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/3k/9y9v3h2j32xb1f804pwqfb780000gn/T/pip-install-h_c38kh2/zerobounce/

```

manually installing `pypandoc` finishes correctly, but `zerobounce` still refuses to install:

```
Collecting zerobounce
  Using cached https://files.pythonhosted.org/packages/f6/45/c064368502a3bc44043584494624f9e8cce0c48039cb594d95a30ba5ba1b/zerobounce-0.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3k/9y9v3h2j32xb1f804pwqfb780000gn/T/pip-install-1fwspmoh/zerobounce/setup.py", line 14, in <module>
        long_description = pypandoc.convert("README.md", "rst"),
      File "/Users/ronenmagid/dev/lstv2/venv/lib/python3.6/site-packages/pypandoc/__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/3k/9y9v3h2j32xb1f804pwqfb780000gn/T/pip-install-1fwspmoh/zerobounce/

```

**Comment by ulriksenstian** [comment]
Any update on this one?

**Comment by Leewaldoe** [comment]
I'm having the same issue

**Comment by thestick613** [comment]
Maybe this one works better: https://github.com/zerobounce/zerobounce-python-api-v2 ?

**Comment by Leewaldoe** [comment]
For those having this issue try `pip3 install sl-zerobounce` instead of `pip3 install zerobounce`
